#include "TCanvas.h"
#include "TLatex.h"
#include "TRestAxionWolterOptics.h"
#include "TRestTask.h"

#ifndef RestTask_Axion_XMMPlots
#define RestTask_Axion_XMMPlots

//*******************************************************************************************************
//*** Description: This macro reads the TRestAxionWolterOptics definition found inside `xmm.rml` and
//*** it will produce different plots after Monte Carlo generation of incoming photons. The plots will
//*** be generated by default at the `/tmp/` directory.
//***
//*** The generated plots are the results from `TRestAxionOptics::DrawScatterMaps`,
//*** `TRestAxionOptics::DrawDensityMaps` and `TRestAxionOptics::DrawParticleTracks`.
//***
//*** --------------
//*** Usage: restManager XMMPlots [z=7000] [energy=1] [deviation=0]
//***
//*** Where the optional arguments are:
//***
//*** - *z*: The additional user optical plane position (in mm) where density and scatter maps should be
//*** drawn.
//*** - *energy*: The energy of the photons.
//*** - *deviation*: Maximum deviation (in radians) respect to optical axis to be given to the MC-photons.
//***
//*******************************************************************************************************
Int_t REST_Axion_XMMPlots(Double_t z = 7000, Double_t eMax = 1, Double_t deviation = 0.0) {
    Int_t nPhotons = 50000;

    TCanvas c("", "", 1200, 1200);

    TRestAxionWolterOptics opt("xmm.rml");
    opt.DrawScatterMaps(z, eMax, deviation, nPhotons);

    std::string fname =
        "/tmp/XMM_SMaps_dev_" + DoubleToString(deviation, "%6.4lf") + "_z_" + DoubleToString(z) + ".png";
    c.Print(fname.c_str());

    TCanvas c2("", "", 1200, 1200);
    opt.DrawDensityMaps(z, eMax, deviation, nPhotons);

    fname = "/tmp/XMM_DMaps_dev_" + DoubleToString(deviation, "%6.4lf") + "_z_" + DoubleToString(z) + ".png";
    c2.Print(fname.c_str());

    TCanvas c1("", "", 1000, 1600);
    opt.DrawParticleTracks(deviation, 30);
    fname = "/tmp/XMM_Tracks_dev_" + DoubleToString(deviation, "%6.4lf") + ".png";
    c1.Print(fname.c_str());

    return 0;
}
#endif
